- id: pyproject-check
  name: Check pyproject.tml syntax and for local paths in uv sources
  description: Ensure that no dependencies have local urls before commit
  entry: pyproject_check
  language: python
  files: ^pyproject.toml$
